### ISSUE TITLE
Query about using everyvoter in an european country

### ISSUE THREAD

**Issue by uladribia** [ofa/everyvoter#4]
Dear all,

Apologies if this questions belongs somewhere else, please do feel free to redirect me to the appropriate place... 

On behalf of an organization, we are interested in applying or expanding existing tools such as everyvoter to our needs. I am just wondering what the effort would be in using it for elections outside the US, in particular in Europe. I have been trying to check the support for OCD for other cities but the docs are not clear in this aspect. So, in short, besides US elections, can other type of elections be added to the platform in a simple way?

Thanks for the info.

Regards,

**Comment by nickcatal** [comment]
EveryVoter heavily references a states table, and the geocoder is specific to US states and districts, so I guess expanding it to canada wouldn't be too difficult but europe would probably be pretty difficult.

**Comment by uladribia** [comment]
Thanks for the information, we will then have to consider some alternatives. Anyhow, good job and thanks for sharing, the package looks amazing ;).
